run:
  # The default timeout is 1 minute, but we can increase it to avoid timeouts on larger projects.
  timeout: 3m

linters:
  # We will explicitly enable the linters mentioned in the guidelines.
  # This ensures we are checking for the specified quality standards.
  enable:
    - errcheck      # Checks for unchecked errors, crucial for robust Go code.
    - goimports     # Enforces consistent import organization and formatting.
    - govet         # Reports common mistakes and suspicious constructs.
    - staticcheck   # A suite of static analysis checks for bugs, performance issues, and simplification.
    - revive        # A modern, configurable replacement for golint.

  # It's good practice to disable linters that are not needed or are overly noisy.
  # For now, we will not disable any explicitly but will stick to the enabled set.

linters-settings:
  goimports:
    # Enforce local prefixes to group imports correctly, aligning with the guidelines.
    local-prefixes: go.robertomontagna.dev/zapfluent

issues:
  exclude-rules:
    # Exclude specific linter rules from test files where they are not critical.
    - path: "_test.go"
      linters:
        - revive
      text: "dot-imports|unused-parameter"

# We can add more configuration here as needed, but this provides a solid baseline
# that directly reflects the project's development documentation.
