package testutil

import (
	"github.com/onsi/gomega"
)

// InterceptGomegaFailuresForTest runs a function and returns a list of failure messages
// generated by Gomega assertions within that function. This is useful for testing
// custom matchers in a standard Go test environment.
//
// This item is for testing purposes only and should not be used in production code.
func InterceptGomegaFailuresForTest(g *gomega.WithT, f func()) []string {
	originalFailHandler := g.Fail
	failures := []string{}
	g.Fail = func(message string, _ ...int) {
		failures = append(failures, message)
	}
	f()
	g.Fail = originalFailHandler
	return failures
}
