package testutil

import (
	"github.com/onsi/gomega"
)

// InterceptGomegaFailures runs a function and returns a list of failure messages
// generated by Gomega assertions within that function. This is useful for testing
// custom matchers in a standard Go test environment.
func InterceptGomegaFailures(g *gomega.WithT, f func()) []string {
	originalFailHandler := g.Fail
	failures := []string{}
	g.Fail = func(message string, _ ...int) {
		failures = append(failures, message)
	}
	f()
	g.Fail = originalFailHandler
	return failures
}
