name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving the accuracy of SonarQube analysis
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true

      - name: Check formatting
        run: make check-fmt

      - name: Lint
        run: make lint

      - name: Run tests and generate reports for CI
        run: make test-ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./report.xml

      # We recommend to only run the SonarQube analysis on the main branch.
      # For more details, see: https://docs.sonarsource.com/sonarqube/latest/devops-platform-integration/github-integration/
      - name: SonarQube Scan
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          # You need to create these secrets in your repository settings.
          # SONAR_HOST_URL should be set to https://sonarcloud.io for SonarCloud.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
